linters-settings:
  govet:
    check-shadowing: false
  gocyclo:
    min-complexity: 30
  misspell:
    locale: US
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/takeshiemoto/go-simple-api)
    skip-generated: true

linters:
  disable-all: true
  enable:
    - goimports
    - unused
    - errcheck
    - gocognit
    - gocyclo
    - gofmt
    - govet
    - misspell
    - staticcheck
    - whitespace
    - gofumpt
