linters-settings:
  govet:
    enable-all: true
    disable:
      - fieldalignment
  gocyclo:
    min-complexity: 30
  misspell:
    locale: US
linters:
  disable-all: true
  enable:
    - goimports
    - unused
    - errcheck
    - gocognit
    - gocyclo
    - gofmt
    - govet
    - misspell
    - staticcheck
    - whitespace
    - gofumpt
    - gci
